  on: [push]
  jobs:
    rust-stable:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Stable Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Build min-sized-rust on Stable
          uses: actions-rs/cargo@v1
          with:
            command: build
        - name: Compute size
          id: compute_size
          run: |
            ls ::set-output name=size:: -lah README.md | awk -F " " {'print $5'}
        - name: Create Size Badge
          uses: schneegans/dynamic-badges-action@v1.1.0
          with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: 3a7cd3ae806ec27a74c3743c5d5a462d
            filename: stable.json
            label: Stable
            message: ${{steps.vars.outputs.size}}
            color: orange


