  on: [push]
  jobs:
    rust-stable:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Stable Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Build debug min-sized-rust on Stable
          uses: actions-rs/cargo@v1
          with:
            command: build
        - name: Build release min-sized-rust on Stable
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release
        - uses: ./.github/actions/get-size-badge
          with:
            path: ./target/debug/min-sized-rust
            badge-filename: stable-debug.json
            auth: ${{secrets.GIST_SECRET}}
        - uses: ./.github/actions/get-size-badge
          with:
            path: ./target/release/min-sized-rust
            badge-filename: stable-release.json
            auth: ${{secrets.GIST_SECRET}}
