  on: [push]
  jobs:
    rust-stable:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Stable Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Build min-sized-rust on Stable
          uses: actions-rs/cargo@v1
          with:
            command: build


