  on: [push]
  jobs:
    rust-stable:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Stable Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Build debug min-sized-rust on Stable
          uses: actions-rs/cargo@v1
          with:
            command: build
        - name: Build release min-sized-rust on Stable
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release
        - name: Compute size
          id: compute_size
          run: |
            echo "SIZE=$(ls -lah ./target/debug/min-sized-rust | awk -F " " {'print $5'})" >> $GITHUB_ENV
        - name: Create Stable Size Badge
          uses: schneegans/dynamic-badges-action@v1.1.0
          with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: 3a7cd3ae806ec27a74c3743c5d5a462d
            filename: ./target/debug/min-sized-rust
            message: ${{env.SIZE}}
            color: brightgreen
        - name: Compute size
          id: compute_size
          run: |
            echo "SIZE=$(ls -lah ./target/release/min-sized-rust | awk -F " " {'print $5'})" >> $GITHUB_ENV
        - name: Create Stable Size Badge
          uses: schneegans/dynamic-badges-action@v1.1.0
          with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: 3a7cd3ae806ec27a74c3743c5d5a462d
            filename: ./target/release/min-sized-rust
            message: ${{env.SIZE}}
            color: brightgreen
